name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-backend:
    name: Build & Test Backend (Flask)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        working-directory: ./api
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

  build-frontend:
    name: Build & Test Frontend (Next.js)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./web
        run: yarn install

      - name: Build frontend
        working-directory: ./web
        run: yarn build
